name: Run SonarQube Scan
description: Run a SonarQube scan to analyze code quality and security
inputs:
  token:
    description: The token to use to authenticate with SonarQube
    required: true
  organization:
    description: The organization in which the project is defined
    required: true
  projectKey:
    description: The key which indicates the project to analyze
    required: true
  url:
    description: The URL of the SonarQube server
    required: false
    default: 'https://sonarcloud.io'
  sourceDir:
    description: The directory containing the source code to analyze
    required: false
    default: '.'
  projectBaseDir:
    description: The base directory of the project
    required: false
    default: '.'
  coverageExclusions:
    description: The files to exclude coverage analysis
    required: false
    default: '**/*_test.go'
  goCoverageReportPaths:
    description: The path to the Go coverage report(s)
    required: false
    default: 'coverage.out'
  excludedWorkflowPattern:
    description: A comma-delimited pattern of workflows to exclude from the security scan
    required: false
    default: ''
  
runs:
  using: 'composite'
  steps:
    - name: Prepare excluded workflow pattern arguments
      id: excluded_workflow_pattern_args
      shell: bash
      run: |
        # Initialize ignore strings
        IDS=""
        ARGS=""
        COUNT=1

        # loop through the input rules
        for PATH in ${{ inputs.excludedWorkflowPattern }}; do
          ID="e$COUNT"

          # build the comma-separated list of IDs
          if [ -z "$IDS" ]; then 
            IDS="$ID"
          else 
            IDS="$IDS,$ID"
          fi
          
          # build the individual property flag
          ARGS="$ARGS -Dsonar.issue.ignore.multicriteria.$ID.ruleKey=githubactions:S7637"
          ARGS="$ARGS -Dsonar.issue.ignore.multicriteria.$ID.resourceKey=${PATH}"
          
          COUNT=$((COUNT + 1))
        done

        if [ ! -z "$IDS" ]; then
          echo "final_args=-Dsonar.issue.ignore.multicriteria=$IDS $ARGS" >> $GITHUB_OUTPUT
        else
          echo "final_args=" >> $GITHUB_OUTPUT
        fi
    - name: Run SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
      env:
        SONAR_TOKEN: ${{ inputs.token }}
      with:
        args: >-
          -Dsonar.host.url=${{ inputs.url }}
          -Dsonar.projectBaseDir=${{ inputs.projectBaseDir }}
          -Dsonar.organization=${{ inputs.organization }}
          -Dsonar.projectKey=${{ inputs.projectKey }}
          -Dsonar.sources=${{ inputs.sourceDir }}
          -Dsonar.coverage.exclusions=${{ inputs.coverageExclusions }}
          -Dsonar.go.coverage.reportPaths=${{ inputs.goCoverageReportPaths }}
          -Dsonar.projectVersion=${{ github.sha }}
          ${{ github.event_name == 'pull_request' && 
            format('-Dsonar.pullrequest.key={0} -Dsonar.pullrequest.branch={1} -Dsonar.pullrequest.base={2}', 
              github.event.pull_request.number, 
              github.head_ref, 
              github.base_ref
            ) 
            || 
            format('-Dsonar.branch.name={0}', 
              github.ref_name
            ) 
          }}
          ${{ steps.excluded_workflow_pattern_args.outputs.final_args }}
